import { useEffect, useMemo, useState } from 'react';
import StoreNavbar from '../components/StoreNavbar';
import { getCatalog } from '../services/catalogService';
import { createOrder } from '../services/orderService';
const money = (v) => `$${Number(v).toLocaleString('es-MX', { minimumFractionDigits: 2 })}`;
export default function Catalog() {
  const [products, setProducts] = useState([]), [cart, setCart] = useState([]), [cartOpen, setCartOpen] = useState(false), [notes, setNotes] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setProducts(await getCatalog()); } catch (e) { setMessage(e.response?.data?.message || 'No se pudo cargar el catálogo'); } finally { setLoading(false); } }; useEffect(() => { load(); }, []);
  const total = useMemo(() => cart.reduce((sum, i) => sum + Number(i.precioVenta) * i.cantidad, 0), [cart]);
  function add(product) { setMessage(''); setCart((items) => { const current = items.find((i) => i.id === product.id); if (current) return items.map((i) => i.id === product.id && i.cantidad < product.stock ? { ...i, cantidad: i.cantidad + 1 } : i); return [...items, { ...product, cantidad: 1 }]; }); }
  function quantity(id, value) { const product = products.find((p) => p.id === id); const cantidad = Math.max(1, Math.min(Number(value) || 1, product.stock)); setCart((items) => items.map((i) => i.id === id ? { ...i, cantidad } : i)); }
  async function order() { if (!cart.length) return; try { await createOrder({ items: cart.map((i) => ({ productoId: i.id, cantidad: i.cantidad })), notas: notes }); setCart([]); setNotes(''); setCartOpen(false); setMessage('Pedido creado. Quedó pendiente de confirmación.'); await load(); } catch (e) { setMessage(e.response?.data?.message || 'No se pudo crear el pedido'); } }
  return <div className="store-page"><StoreNavbar cartCount={cart.length} onCartClick={() => setCartOpen(!cartOpen)} />{message && <p className="store-message">{message}</p>}<section className="store-hero"><p>DROP // AVAILABLE NOW</p><h1>SKULL FACE<br />STREETWEAR</h1><span>PIEZAS DISPONIBLES · ENTREGA A CONFIRMAR</span></section><main className="catalog-grid">{loading ? <div className="empty-state">Cargando catálogo...</div> : products.map((p) => <article className="catalog-card" key={p.id}><div className="catalog-image">{p.imagen ? <img src={p.imagen} alt={p.nombre} /> : <span>☠</span>}</div><div className="catalog-meta"><small>{p.categoria} // {p.color}</small><h2>{p.nombre}</h2><p>Talla {p.talla} · {p.stock} disponibles</p><div><strong>{money(p.precioVenta)}</strong><button className="btn-primary" onClick={() => add(p)}>Agregar</button></div></div></article>)}</main>{cartOpen && <aside className="cart-panel"><div className="panel-header"><h3>Carrito</h3><button className="btn-icon" onClick={() => setCartOpen(false)}>✕</button></div>{cart.map((i) => <div className="cart-line" key={i.id}><span>{i.nombre}</span><input type="number" min="1" max={i.stock} value={i.cantidad} onChange={(e) => quantity(i.id, e.target.value)} /><span>{money(i.precioVenta * i.cantidad)}</span><button className="btn-icon btn-icon-danger" onClick={() => setCart(cart.filter((p) => p.id !== i.id))}>✕</button></div>)}<label className="cart-notes">Notas<textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Opcional" /></label><div className="sale-total"><span>TOTAL</span><span>{money(total)}</span></div><button disabled={!cart.length} className="btn-primary btn-block" onClick={order}>Crear pedido</button></aside>}</div>;
}
